InsuranceTrancking/InsuranceTrancking/Controllers/customersController.cs
using InsuranceTrancking.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace InsuranceTrancking.Controllers
{
    public class customersController : MController
    {
        private Model1 db = new Model1();

        // GET: customers
       
        public ActionResult Index()
        {
            return View(db.customers.ToList());
        }

        // GET: customers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customers customers = db.customers.Find(id);
            if (customers == null)
            {
                return HttpNotFound();
            }
            return View(customers);
        }

        // GET: customers/Create
        
        public ActionResult Create()
        {
            ViewBag.InsuranceCompanyID = db.insurance_companies.ToList() ?? new List<InsuranceTrancking.Models.insurance_companies>();
            return View();
        }

        // POST: customers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        
        public ActionResult Create([Bind(Include = "CustomerID,FirstName,LastName,PhoneNumber,Email,Address,IsAdmin")] customers customers)
        {
            if (ModelState.IsValid)
            {
                db.customers.Add(customers);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.InsuranceCompanyID = db.insurance_companies.ToList() ?? new List<InsuranceTrancking.Models.insurance_companies>();
            return View(customers);
        }
        //public ActionResult CreateWithVehicle()
        //{
        //    return RedirectToAction("Index");
        //}
        [HttpPost]
        
        public ActionResult CreateWithVehicle(customers customer, vehicles vehicles, insurance_policies insurance_Policies)
        {
            if (ModelState.IsValid)
            {
                // Step 1: Add the customer to the database. CustomerID will be auto-generated.
                db.customers.Add(customer);
                db.SaveChanges();  // This will insert the customer and generate a CustomerID

                // Step 2: Ensure vehicles are assigned to this customer
                //foreach (var vehicle in vehicles)
                //{
                //    vehicle.CustomerID = customer.CustomerID;  // Link vehicle to the newly created customer
                //    db.vehicles.Add(vehicle);
                //}
                vehicles.CustomerID = customer.CustomerID;
                db.vehicles.Add(vehicles);
                db.SaveChanges();

                insurance_Policies.CustomerID = customer.CustomerID;
                insurance_Policies.VehicleID = vehicles.VehicleID;
                db.insurance_policies.Add(insurance_Policies);
                db.SaveChanges();


                // Step 3: Save the vehicles
              //  db.SaveChanges();

                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Please fill in all required fields.");

            ViewBag.InsuranceCompanyID = db.insurance_companies.ToList() ?? new List<InsuranceTrancking.Models.insurance_companies>();
            return View(customer);  // If model is invalid, return the view
        }



        // GET: customers/Edit/5

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customers customers = db.customers.Find(id);
            if (customers == null)
            {
                return HttpNotFound();
            }
            return View(customers);
        }

        // POST: customers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]

        public ActionResult Edit([Bind(Include = "CustomerID,FirstName,LastName,PhoneNumber,Email,Address,IsAdmin")] customers customers)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customers).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customers);
        }

        // GET: customers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customers customers = db.customers.Find(id);
            if (customers == null)
            {
                return HttpNotFound();
            }
            return View(customers);
        }

        // POST: customers/Delete/5
        [HttpPost, ActionName("Delete")]
        // [ValidateAntiForgeryToken]

        // [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            using (var transaction = db.Database.BeginTransaction())
            {
                try
                {
                    // Find the customer
                    customers customer = db.customers.Find(id);
                    if (customer == null)
                    {
                        return HttpNotFound();
                    }

                    // Delete related accident reports
                    var vehicles = db.vehicles.Where(v => v.CustomerID == id).ToList();
                    foreach (var vehicle in vehicles)
                    {
                        var accidentReports = db.accident_reports.Where(ar => ar.VehicleID == vehicle.VehicleID).ToList();
                        db.accident_reports.RemoveRange(accidentReports);
                    }

                    // Delete related payments for policies
                    var policies = db.insurance_policies.Where(p => p.CustomerID == id).ToList();
                    foreach (var policy in policies)
                    {
                        var payments = db.payments.Where(pay => pay.PolicyID == policy.PolicyID).ToList();
                        db.payments.RemoveRange(payments);
                    }

                    // Delete related insurance policies
                    db.insurance_policies.RemoveRange(policies);

                    // Delete related vehicles
                    db.vehicles.RemoveRange(vehicles);

                    // Delete related driving license
                    var license = db.driving_license.FirstOrDefault(dl => dl.CustomerID == id);
                    if (license != null)
                    {
                        db.driving_license.Remove(license);
                    }

                    // Delete the customer
                    db.customers.Remove(customer);

                    // Save changes and commit transaction
                    db.SaveChanges();
                    transaction.Commit();
                }
                catch (Exception)
                {
                    // Rollback transaction if an error occurs
                    transaction.Rollback();
                    throw;
                }
            }

            return RedirectToAction("Index");
        }


       
    }
}

InsuranceTrancking/InsuranceTrancking/Controllers/vehiclesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using InsuranceTrancking.Models;

namespace InsuranceTrancking.Controllers
{
    public class vehiclesController : MController
    {
        private Model1 db = new Model1();

        // GET: vehicles
        public ActionResult Index()
        {
            var vehicles = db.vehicles.Include(v => v.customers);
            return View(vehicles.ToList());
        }

        // GET: vehicles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            vehicles vehicles = db.vehicles.Find(id);
            if (vehicles == null)
            {
                return HttpNotFound();
            }
            return View(vehicles);
        }

        // GET: vehicles/Create
        public ActionResult Create()
        {


            ViewBag.Customers = db.customers.ToList() ?? new List<InsuranceTrancking.Models.customers>();
            return View();

        }

        
        [HttpPost]
        
       



        // GET: vehicles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            vehicles vehicles = db.vehicles.Find(id);
            if (vehicles == null)
            {
                return HttpNotFound();
            }
            ViewBag.Customers = db.customers.ToList();
            return View(vehicles);
        }

        // POST: vehicles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
      //  [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CustomerID,VehicleID,Brand,Model,Plate,Year,CustomerClaimDate")] vehicles vehicles)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vehicles).State = EntityState.Modified;
                db.SaveChanges();//->hata
                return RedirectToAction("Index");
            }
            ViewBag.Customers = db.customers.ToList();
            return View(vehicles);
        }

        // GET: vehicles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            vehicles vehicles = db.vehicles.Find(id);
            if (vehicles == null)
            {
                return HttpNotFound();
            }
            return View(vehicles);
        }

        // POST: vehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            using (var transaction = db.Database.BeginTransaction())
            {
                try
                {
                    // Find the vehicle
                    vehicles vehicle = db.vehicles.Find(id);
                    if (vehicle == null)
                    {
                        return HttpNotFound();
                    }

                    // Delete related accident reports linked to insurance policies
                    var insurancePolicies = db.insurance_policies.Where(i => i.VehicleID == id).ToList();
                    foreach (var policy in insurancePolicies)
                    {
                        var relatedAccidentReports = db.accident_reports.Where(ar => ar.PolicyID == policy.PolicyID).ToList();
                        if (relatedAccidentReports.Any())
                        {
                            db.accident_reports.RemoveRange(relatedAccidentReports);
                        }
                    }

                    // Delete related insurance policies
                    if (insurancePolicies.Any())
                    {
                        db.insurance_policies.RemoveRange(insurancePolicies);
                    }

                    // Delete related accident reports directly linked to the vehicle
                    var vehicleAccidentReports = db.accident_reports.Where(a => a.VehicleID == id).ToList();
                    if (vehicleAccidentReports.Any())
                    {
                        db.accident_reports.RemoveRange(vehicleAccidentReports);
                    }

                    // Delete the vehicle
                    db.vehicles.Remove(vehicle);

                    // Save changes and commit transaction
                    db.SaveChanges();
                    transaction.Commit();
                }
                catch (Exception ex)
                {
                    // Rollback transaction in case of error
                    transaction.Rollback();
                    // Log the error
                    System.Diagnostics.Debug.WriteLine($"Error deleting vehicle with ID {id}: {ex.Message}");
                    throw;
                }
            }

            return RedirectToAction("Index");
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

InsuranceTrancking/InsuranceTrancking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DOU Sigorta</title>
    <link rel="icon" href="https://i.hizliresim.com/mypwusf.png" type="image/png">
    <link rel="stylesheet" href="~/Content/Layout.css">


    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")




</head>


<body>

    <div class="wrapper">
        <!-- Brand Div -->
        <div class="brand-div">
            <a href="https://localhost:44349/home/index"><img src="https://i.hizliresim.com/mypwusf.png" alt="DOU Sigorta Logo"></a>
            <a href="https://localhost:44349/home/index">DOU SİGORTA</a>
            
        </div>

        <div class="menu-div dropdown-center">
            <ul class="nav">
                <!-- Customer Dropdown -->
                <li class="nav-item dropdown @(Request.Url.AbsolutePath.Contains("/customers") ? "active" : "")">
                    <a class="nav-link dropdown" href="/customers/Index" id="customerDropdown">
                        Customer
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="customerDropdown">
                        <li class="dropdown-item">@Html.ActionLink("Customer List", "Index", "customers", null, new { @class = "dropdown-item" })</li>
                        <li class="dropdown-item">@Html.ActionLink("Create", "Create", "customers", null, new { @class = "dropdown-item" })</li>
                    </ul>
                </li>

                <!-- Vehicle Dropdown -->
                <li class="nav-item dropdown @(Request.Url.AbsolutePath.Contains("/vehicles") ? "active" : "")">
                    <a class="nav-link dropdown" href="/vehicles/Index" id="vehicleDropdown">
                        Vehicle
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="vehicleDropdown">
                        <li class="dropdown-item">@Html.ActionLink("Vehicle List", "Index", "vehicles", null, new { @class = "dropdown-item" })</li>
                        <li class="dropdown-item">@Html.ActionLink("Create", "Create", "vehicles", null, new { @class = "dropdown-item" })</li>
                    </ul>
                </li>

                <!-- Insurance Policies Dropdown -->
                <li class="nav-item dropdown @(Request.Url.AbsolutePath.Contains("/insurance_policies") ? "active" : "")">
                    <a class="nav-link dropdown" href="/insurance_policies/Index" id="insurancePoliciesDropdown">
                        Insurance Policies
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="insurancePoliciesDropdown">
                        <li class="dropdown-item">@Html.ActionLink("Insurance Policies List", "Index", "insurance_policies", null, new { @class = "dropdown-item" })</li>
                        <li class="dropdown-item">@Html.ActionLink("Create", "Create", "insurance_policies", null, new { @class = "dropdown-item" })</li>
                    </ul>
                </li>

                <!-- Accident Report Dropdown -->
                <li class="nav-item dropdown @(Request.Url.AbsolutePath.Contains("/accident_reports") ? "active" : "")">
                    <a class="nav-link dropdown" href="/accident_reports/Index" id="accidentReportDropdown">
                        Accident Report
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="accidentReportDropdown">
                        <li class="dropdown-item">@Html.ActionLink("Accident Report List", "Index", "accident_reports", null, new { @class = "dropdown-item" })</li>
                        <li class="dropdown-item">@Html.ActionLink("Create", "Create", "accident_reports", null, new { @class = "dropdown-item" })</li>
                    </ul>
                </li>
                <nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-left:42%">

                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav ml-auto">

                            @if (Session["User"] != null)
                            {
                                <li class="nav-item">
                                    <a class="nav-link" href="@Url.Action("Logout", "Login")" style=" font-weight: bold;">Logout</a>
                                </li>
                            }
                        </ul>
                    </div>
                </nav>

            </ul>
        </div>

        <!-- İçerik -->
        <div class="container body-content">
            @RenderBody()
        </div>

        <!-- Footer -->
        <footer>
            <p>&copy; @DateTime.Now.Year - DOU Sigorta</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>